### ISSUE TITLE
Write of debugging files

### ISSUE THREAD

**Issue by cmbntr** [EliotJones/BigGustave#5]
Hi @EliotJones,

In the released library version 1.0.2 there are some `File.WriteAllBytes(@"C:\temp\...` calls present, which cause the library to fail.

For example in `PngBuilder.cs` on line 30.

Best regards,
Michael

**Comment by EliotJones** [comment]
Hi @cmbntr,

Thanks for letting me know, that's an embarrasing bug 😆 I have published a new version 1.0.3, without this code in. Apologies for the bug.
