### ISSUE TITLE
Writing metadata in the png file

### ISSUE THREAD

**Issue by siva538** [EliotJones/BigGustave#6]
Hello @EliotJones , Thank you for the library!

Is there a possibility of writing data in the png file?  We wanted to store metadata something similar to the badge baking option available in - https://github.com/concentricsky/openbadges-bakery 

Thanks in advance.

**Comment by EliotJones** [comment]
Hi @siva538 I appreciate it's probably too late to be useful to you now but I've pushed a change which enables using `pngBuilder.StoreText(keyword, title);` to store arbitrary text data in the PNG in a spec-compliant way.

**Comment by grimmlen** [comment]
Could we get a new release that includes this chnage?

**Comment by EliotJones** [comment]
@grimmlen :shipit: this is now available in 1.0.5 https://www.nuget.org/packages/BigGustave

**Comment by grimmlen** [comment]
Woot! Thanks so much! Already using StoreText()
